<?php

/**
 * @file
 * This files demonstrates how to use hook functions.
 */


/**
 * Implements hook_cron().
 */
function mymodule_cron() {
  Drupal::messenger()->addMessage('Hello from mymodule cron hook! :) :)');
}

/**
 * Implements hook_form_alter
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {

//  Drupal::messenger()->addMessage(t("form_id of this form is @id: ", ['@id' => $form_id]));

  /*
   * Alter the form submit button text when editing an Article node.
   */
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t("Save this awesome article!");
  }
}
